In [1]:
import numpy as np

list=[1,2,3,4]
hi_arr=np.array(list)


In [3]:
print(hi_arr)

[1 2 3 4]


In [4]:
type(hi_arr)

numpy.ndarray

In [10]:
list_1=[1,2,3,4]
list_2=[2,3,4,5]
list_3=[1,2,3,4]
hi_arrs=np.array([list_1,list_2,list_3])
print(hi_arrs)

[[1 2 3 4]
 [2 3 4 5]
 [1 2 3 4]]


In [11]:
type(hi_arrs)

numpy.ndarray

In [12]:
hi_arrs.shape

(3, 4)

In [15]:
#indexing
lists=[1,2,3,4]
hi_ar=np.array(lists)
hi_ar

array([1, 2, 3, 4])

In [16]:
hi_ar[3]

4

In [18]:
hi_ar[1]


2

In [20]:
ji_li=[1,23,3]
ji_li1=[1,2,3]
ji_li2=[1,2,3]
arr=np.array([ji_li,ji_li1,ji_li2])
arr


array([[ 1, 23,  3],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [21]:
arr[1:2,0:3]

array([[1, 2, 3]])

In [22]:
arr[:,:]

array([[ 1, 23,  3],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [23]:
arr[0:,0:1]

array([[1],
       [1],
       [1]])

array([[  1,  23,   3],
       [  1,   2,   3],
       [100, 100, 100]])

In [30]:
arr[1:2,0:1]=200
arr

array([[  1,  23,   3],
       [200,   2,   3],
       [100, 100, 100]])

In [31]:
val=2
arr[arr<3]

array([1, 2])

In [33]:
hi=np.arange(0,20).reshape(5,4)
hi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
hi1=np.arange(0,20).reshape(5,4)
hi1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
hi*hi1

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [43]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.random.rand(3,3)

array([[0.38789201, 0.44062862, 0.14473182],
       [0.32810154, 0.51607918, 0.87508519],
       [0.15781525, 0.69551716, 0.71703416]])

In [46]:
# to make matrix zerors and ones 
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
#random values
np.random.rand(3,3)

array([[0.99410168, 0.84436051, 0.27099949],
       [0.3882374 , 0.92883412, 0.4483658 ],
       [0.7905395 , 0.41339907, 0.54639466]])

In [50]:
np.random.rand(4,4)

array([[0.69804639, 0.63330681, 0.40751278, 0.47991696],
       [0.9067565 , 0.07797194, 0.9359412 , 0.42284664],
       [0.05147269, 0.43495172, 0.04720048, 0.05811614],
       [0.55521808, 0.18056185, 0.99260937, 0.15269309]])

In [51]:
np.random.randint(0,100,8).reshape(4,2)

array([[39, 71],
       [63, 73],
       [55, 52],
       [14, 74]])

In [53]:
list=[1,2,3,4]
arr_1=np.array(list)
arr_1

array([1, 2, 3, 4])

In [54]:
type(arr_1)

numpy.ndarray

In [55]:
list1=[1,2,3,4]
list2=[2,3,4,5]
list3=[1,2,3,4]
a=np.array([list1,list2,list3])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [56]:
type(a)

numpy.ndarray

In [57]:
arr_1[3]

4

In [58]:
a[0:,:]

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [59]:
a[1:2,0:1]

array([[2]])

In [60]:
a.shape

(3, 4)

In [62]:
a[1:2,0:1]=100
print(a)

[[  1   2   3   4]
 [100   3   4   5]
 [  1   2   3   4]]


In [67]:
b=np.arange(0,10).reshape(2,5)
c=np.arange(0,10).reshape(2,5)
print(b)
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [68]:
b*c

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [69]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
np.random.rand(4,4)

array([[0.56818094, 0.90285477, 0.32259247, 0.83391668],
       [0.5585071 , 0.10587274, 0.25514726, 0.15225557],
       [0.72919085, 0.12698793, 0.34630566, 0.98441402],
       [0.58415831, 0.55964896, 0.96600761, 0.20908792]])

In [75]:
np.random.randint(0,10,8).reshape(2,3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [77]:
np.random.random_sample((1,4))

array([[0.69617034, 0.65629011, 0.39833647, 0.14635515]])