In [16]:
import pandas as pd
import numpy as np

dft=pd.DataFrame(np.arange(0,10).reshape(2,5),index=['A','B'],columns=['1','5','2','3','4'])
dft

1  5  2  3  4
A  0  1  2  3  4
B  5  6  7  8  9

In [5]:
dft.head()

1  1  2  3  4
A  0  1  2  3  4
B  5  6  7  8  9

In [7]:
dft.loc['A']

1    0
1    1
2    2
3    3
4    4
Name: A, dtype: int32

In [9]:
dft.iloc[0:1,0:1]

1
A  0

In [10]:
dft.iloc[1:2,1:2]

1
B  6

In [11]:
dft.iloc[:,:]

1  1  2  3  4
A  0  1  2  3  4
B  5  6  7  8  9

In [12]:
dft.iloc[:,1:].values

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [14]:
dft.iloc[0:1,1:]

1  2  3  4
A  1  2  3  4

In [17]:
dft['5'].value_counts()

5
1    1
6    1
Name: count, dtype: int64

In [19]:
dft['3'].value_counts()

3
3    1
8    1
Name: count, dtype: int64

In [20]:
dft.head()

1  5  2  3  4
A  0  1  2  3  4
B  5  6  7  8  9

In [21]:
dft.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, A to B
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       2 non-null      int32
 1   5       2 non-null      int32
 2   2       2 non-null      int32
 3   3       2 non-null      int32
 4   4       2 non-null      int32
dtypes: int32(5)
memory usage: 56.0+ bytes


In [22]:
dft.describe()

1         5         2         3         4
count  2.000000  2.000000  2.000000  2.000000  2.000000
mean   2.500000  3.500000  4.500000  5.500000  6.500000
std    3.535534  3.535534  3.535534  3.535534  3.535534
min    0.000000  1.000000  2.000000  3.000000  4.000000
25%    1.250000  2.250000  3.250000  4.250000  5.250000
50%    2.500000  3.500000  4.500000  5.500000  6.500000
75%    3.750000  4.750000  5.750000  6.750000  7.750000
max    5.000000  6.000000  7.000000  8.000000  9.000000

In [26]:
ed=pd.DataFrame(np.arange(0,12).reshape(3,4),index=['boyfriend','girlfriend','friend'],columns=['hi','hello','bye','hiii'])
ed
                

hi  hello  bye  hiii
boyfriend    0      1    2     3
girlfriend   4      5    6     7
friend       8      9   10    11

In [27]:
ed.head()

hi  hello  bye  hiii
boyfriend    0      1    2     3
girlfriend   4      5    6     7
friend       8      9   10    11

In [28]:
ed.loc['boyfriend']

hi       0
hello    1
bye      2
hiii     3
Name: boyfriend, dtype: int32

In [29]:
ed.loc['girlfriend']

hi       4
hello    5
bye      6
hiii     7
Name: girlfriend, dtype: int32

In [30]:
type(ed.loc['boyfriend'])

pandas.core.series.Series

In [32]:
ed.iloc[:,:]

hi  hello  bye  hiii
boyfriend    0      1    2     3
girlfriend   4      5    6     7
friend       8      9   10    11

In [34]:
ed.iloc[0:2,1:2]

hello
boyfriend       1
girlfriend      5

In [35]:
dft.iloc[:,1:].values

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [37]:
ed.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [38]:
ed['hi'].value_counts()

hi
0    1
4    1
8    1
Name: count, dtype: int64

In [39]:
ed['hiii'].value_counts()

hiii
3     1
7     1
11    1
Name: count, dtype: int64

In [40]:
ed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, boyfriend to friend
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hi      3 non-null      int32
 1   hello   3 non-null      int32
 2   bye     3 non-null      int32
 3   hiii    3 non-null      int32
dtypes: int32(4)
memory usage: 180.0+ bytes


In [41]:
ed.corr()

hi  hello  bye  hiii
hi     1.0    1.0  1.0   1.0
hello  1.0    1.0  1.0   1.0
bye    1.0    1.0  1.0   1.0
hiii   1.0    1.0  1.0   1.0

In [42]:
ed.head()

hi  hello  bye  hiii
boyfriend    0      1    2     3
girlfriend   4      5    6     7
friend       8      9   10    11

In [43]:
ed.describe()

hi  hello   bye  hiii
count  3.0    3.0   3.0   3.0
mean   4.0    5.0   6.0   7.0
std    4.0    4.0   4.0   4.0
min    0.0    1.0   2.0   3.0
25%    2.0    3.0   4.0   5.0
50%    4.0    5.0   6.0   7.0
75%    6.0    7.0   8.0   9.0
max    8.0    9.0  10.0  11.0

In [44]:
ed['hi'].value_counts()

hi
0    1
4    1
8    1
Name: count, dtype: int64

In [45]:
ed['hiii'].value_counts()

hiii
3     1
7     1
11    1
Name: count, dtype: int64

In [46]:
ed[ed['hi']>100]

Empty DataFrame
Columns: [hi, hello, bye, hiii]
Index: []

In [49]:
ash=pd.DataFrame(np.arange(0,10).reshape(2,5),index=['1','2'],columns=['dude','hii','dii','hi','bye'])
ash

dude  hii  dii  hi  bye
1     0    1    2   3    4
2     5    6    7   8    9

In [52]:
ash.loc['1']

dude    0
hii     1
dii     2
hi      3
bye     4
Name: 1, dtype: int32

In [53]:
ash.iloc[1:,2:]

dii  hi  bye
2    7   8    9

In [54]:
ash.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   dude    2 non-null      int32
 1   hii     2 non-null      int32
 2   dii     2 non-null      int32
 3   hi      2 non-null      int32
 4   bye     2 non-null      int32
dtypes: int32(5)
memory usage: 164.0+ bytes


In [55]:
ash.corr()

dude  hii  dii   hi  bye
dude   1.0  1.0  1.0  1.0  1.0
hii    1.0  1.0  1.0  1.0  1.0
dii    1.0  1.0  1.0  1.0  1.0
hi     1.0  1.0  1.0  1.0  1.0
bye    1.0  1.0  1.0  1.0  1.0

In [56]:
ash.head()

dude  hii  dii  hi  bye
1     0    1    2   3    4
2     5    6    7   8    9

In [57]:
ash.describe()

dude       hii       dii        hi       bye
count  2.000000  2.000000  2.000000  2.000000  2.000000
mean   2.500000  3.500000  4.500000  5.500000  6.500000
std    3.535534  3.535534  3.535534  3.535534  3.535534
min    0.000000  1.000000  2.000000  3.000000  4.000000
25%    1.250000  2.250000  3.250000  4.250000  5.250000
50%    2.500000  3.500000  4.500000  5.500000  6.500000
75%    3.750000  4.750000  5.750000  6.750000  7.750000
max    5.000000  6.000000  7.000000  8.000000  9.000000